### ISSUE TITLE
Invalid Vendor code

### ISSUE THREAD

**Issue by bhaskar-c** [Shoonya-Dev/ShoonyaApi-js#1]
Hey 

I have been trying to run this demo. I get the following error response:

`    data: { stat: 'Not_Ok', emsg: 'Invalid Input :  Invalid Vendor code' }`

What would be the `vendor_code` that I should fill in the file  `cred.js` ?

**Comment by suresh-n** [comment]
client client code with _U  "FA00000_U"

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

You need to Put  client code with _U, For Example:-  "FA12345_U"
