### ISSUE TITLE
look like the RestApi.js is broken seeing syntaxError

### ISSUE THREAD

**Issue by suresh-n** [Shoonya-Dev/ShoonyaApi-js#10]
ShoonyaApi-js/lib/RestApi.js:421
          if product_type != '':
             ^^^^^^^^^^^^

SyntaxError: Unexpected identifier

**Comment by suresh-n** [comment]
any update on this ?

**Comment by suresh-n** [comment]
@kambalatech   any update on this ?

**Comment by helagoddr** [comment]
if (product_type != ''){
            values["prd"]       = product_type       
    }

change if condition like this @suresh-n
