### ISSUE TITLE
unable to login with api

### ISSUE THREAD

**Issue by helagoddr** [Shoonya-Dev/ShoonyaApi-js#11]
getting below error

Reply:  {
  request_time: '19:51:00 22-10-2022',
  stat: 'Not_Ok',
  emsg: 'Invalid Input : Invalid OTP'
}

**Comment by suresh-n** [comment]
try insert the below  code to cred.js top and  change the 'twoFA'   to  token variable.
 
```
const totp = require("totp-generator");
const token = totp("authcode");  //change the authcode to authenticator code from the shoonya web.
console.log(token); 
```

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

EMSG: 'Invalid Input: Invalid OTP' comes when you enter the wrong or expired otp or totp in OTP or TOTP field

Hope your issue has been resolved with the shared solution by @suresh-n
