### ISSUE TITLE
Response: { status: 500, message: 'Error' }

### ISSUE THREAD

**Issue by neerajgupta2407** [Shoonya-Dev/ShoonyaApi-js#12]
When i am calling Limit API or any other API, first time i get the response , but when i call the same api again , response received is { status: 500, message: 'Error' }

As mentioned in Document, per second rate limit is 20 but i don't think that's the case here.
https://finvasia.com/api-documentation#ratelimit
I think 500 is returned by Cloudflare .

Any suggestions?

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

Currently, in our API, we provide 20 orders per second per service instance & 200 orders per minute per service instance.
What you are seeing status: 500 is the error code. The HTTP status code 500 is a generic error response. It means that the server encountered an unexpected condition that prevented it from fulfilling the request.

Team Shoonya By Finvasia
