### ISSUE TITLE
Are GTT orders available via nodejs?

### ISSUE THREAD

**Issue by arshmakker** [Shoonya-Dev/ShoonyaApi-js#2]
hi,

I see that the Shoonya API has the ability to put GTT orders. 
Screenshot of API documentation. 
<img width="1440" alt="Screenshot 2022-01-29 at 10 21 45 AM" src="https://user-images.githubusercontent.com/6174092/151647826-5bd418e1-5345-4310-bc33-5152682f9c9a.png">

I would like to use nodeJs client to manage GTT orders, is it possible? I could not find any examples or the documentation in nodeJS  client, could you clarify?

Please confirm
Regards
Arsh

**Comment by Shoonya-Dev** [comment]
Greetings from FINVASIA!

Thanks for your Concern.

You Can Function Call to Our REST API from NODEJS.
